# MLWorkflow with scikit-learn
This notebook contains a complete ML workflow solution using scitkit-learn.  
  
It is based on a course taught by Kevin Markham of the Data School.

## Purpose
This notebook provides an example of an end-to-end ML processing workflow for a 

## Outline  
1. Review of the basic ML Workflow
2. Encoding categorical data
3. Using ColumnTransformaer and Pipeline
4. Encoding test data
5. Handling missing values
6. Switching to the full dataset
7. Evaluating and tuning a pipeline
  
## WIP - improvements
Use this section only if the notebook is not final.

Notable TODOs:
- todo 1;
- todo 2;
- todo 3.

## Results
Describe and comment the most important results.

## Suggested next steps
State suggested next steps, based on results obtained in this notebook.

# Setup

## Library import
We import all the required Python libraries

In [3]:
# Data manipulation
import pandas as pd
import numpy as np
import sklearn as sk

# Options for pandas
pd.options.display.max_columns = 50
pd.options.display.max_rows = 30

# Visualizations
import plotly
import plotly.graph_objs as go
import plotly.offline as ply
plotly.offline.init_notebook_mode(connected=True)

import matplotlib as plt

# Autoreload extension
if 'autoreload' not in get_ipython().extension_manager.loaded:
    %load_ext autoreload
    
%autoreload 2

## Local library import
We import all the required local libraries libraries

In [2]:
# Include local library paths
import sys
# sys.path.append('path/to/local/lib') # uncomment and fill to import local libraries

# Import local libraries

# Part One
Review of the basic Machine Learning Workflow.

In [5]:
df = pd.read_csv('http://bit.ly/kaggletrain', nrows=10)
print(df)

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54

In [11]:
X = df[['Parch', 'Fare']]
X.shape
X

Parch     Fare
0      0   7.2500
1      0  71.2833
2      0   7.9250
3      0  53.1000
4      0   8.0500
5      0   8.4583
6      0  51.8625
7      1  21.0750
8      2  11.1333
9      0  30.0708

In [12]:
y = df['Survived']
y.shape
y

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: Survived, dtype: int64

In [13]:
from sklearn.linear_model import LogisticRegression

In [16]:
logreg = LogisticRegression(solver='liblinear', random_state=1)

In [18]:
from sklearn.model_selection import cross_val_score
cross_val_score(logreg, X, y, cv=3, scoring='accuracy')

array([0.75      , 0.66666667, 0.66666667])

In [19]:
logreg.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
df_new = pd.read_csv('http://bit.ly/kaggletest', nrows=10)
df_new

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
5          897       3                    Svensson, Mr. Johan Cervin    male   
6          898       3                          Connolly, Miss. Kate  female   
7          899       2                  Caldwell, Mr. Albert Francis    male   
8          900       3     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female   
9          901       3                       Davies, Mr. John Samuel    male   

    Age  SibSp  Parch     Ticket     Fare  Cabin Embarked  
0  34.5      0      0     330911   7.8292    NaN        Q  
1  47.0      1      0     363272   7.0000    NaN        S  
2  62.0      0      0     240276   9.6875    NaN        Q  
3  27.0      0      0     315154   8.6625    NaN        S  
4  22.0      1      1    3101298  12.2875    NaN        S  
5  14.0      0      0       7538   9.2250    NaN        S  
6  30.0      0      0     330972   7.6292    NaN        Q  
7  26.0      1      1     248738  29.0000    NaN        S  
8  18.0      0      0       2657   7.2292    NaN        C  
9  21.0      2      0  A/4 48871  24.1500    NaN        S

In [22]:
X_new = df_new[['Parch', 'Fare']]
X_new

Parch     Fare
0      0   7.8292
1      0   7.0000
2      0   9.6875
3      0   8.6625
4      1  12.2875
5      0   9.2250
6      0   7.6292
7      1  29.0000
8      0   7.2292
9      0  24.1500

In [23]:
logreg.predict(X_new)

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1])

# Part Two  
Encoding categorical data

In [24]:
df

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [29]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe.fit_transform(df[['Embarked']])

<10x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [32]:
ohe.categories_

[array(['C', 'Q', 'S'], dtype=object)]

In [33]:
ohe.fit_transform(df[['Embarked', 'Sex']])

<10x5 sparse matrix of type '<class 'numpy.float64'>'
	with 20 stored elements in Compressed Sparse Row format>

# Part Three
Using ColumnTransformer and Pipeline

In [34]:
cols = ['Parch', 'Fare', 'Embarked', 'Sex']

In [35]:
X = df[cols]
X

Parch     Fare Embarked     Sex
0      0   7.2500        S    male
1      0  71.2833        C  female
2      0   7.9250        S  female
3      0  53.1000        S  female
4      0   8.0500        S    male
5      0   8.4583        Q    male
6      0  51.8625        S    male
7      1  21.0750        S    male
8      2  11.1333        S  female
9      0  30.0708        C  female

In [36]:
ohe = OneHotEncoder()

In [37]:
from sklearn.compose import make_column_transformer

In [38]:
ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']),
    remainder='passthrough')

In [39]:
ct.fit_transform(X)

array([[ 0.    ,  0.    ,  1.    ,  0.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    , 71.2833],
       [ 0.    ,  0.    ,  1.    ,  1.    ,  0.    ,  0.    ,  7.925 ],
       [ 0.    ,  0.    ,  1.    ,  1.    ,  0.    ,  0.    , 53.1   ],
       [ 0.    ,  0.    ,  1.    ,  0.    ,  1.    ,  0.    ,  8.05  ],
       [ 0.    ,  1.    ,  0.    ,  0.    ,  1.    ,  0.    ,  8.4583],
       [ 0.    ,  0.    ,  1.    ,  0.    ,  1.    ,  0.    , 51.8625],
       [ 0.    ,  0.    ,  1.    ,  0.    ,  1.    ,  1.    , 21.075 ],
       [ 0.    ,  0.    ,  1.    ,  1.    ,  0.    ,  2.    , 11.1333],
       [ 1.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    , 30.0708]])

In [41]:
from sklearn.pipeline import make_pipeline

In [42]:
# two step pipeline
pipe = make_pipeline(ct, logreg)

In [43]:
pipe.fit(X, y)

Pipeline(memory=None,
         steps=[('columntransformer',
                 ColumnTransformer(n_jobs=None, remainder='passthrough',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories='auto',
                                                                drop=None,
                                                                dtype=<class 'numpy.float64'>,
                                                                handle_unknown='error',
                                                                sparse=True),
                                                  ['Embarked', 'Sex'])],
                                   verbose=False)),
                ('logisticregression',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                         

In [44]:
# same steps covered as with pipe.fit
logreg.fit(ct.fit_transform(X), y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [45]:
# show coef during the steps
pipe.named_steps.logisticregression.coef_

array([[ 0.26491287, -0.19848033, -0.22907928,  1.0075062 , -1.17015293,
         0.20056557,  0.01597307]])

In [47]:
X_new = df_new[cols]
X_new

Parch     Fare Embarked     Sex
0      0   7.8292        Q    male
1      0   7.0000        S  female
2      0   9.6875        Q    male
3      0   8.6625        S    male
4      1  12.2875        S  female
5      0   9.2250        S    male
6      0   7.6292        Q  female
7      1  29.0000        S    male
8      0   7.2292        C  female
9      0  24.1500        S    male

In [48]:
pipe.predict(X_new)

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [49]:
#same steps as pipe.predict
logreg.predict(ct.transform(X_new))

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

## Recap

http://bit.ly/basic-pipeline

In [50]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

cols = ['Parch', 'Fare', 'Embarked', 'Sex']

df = pd.read_csv('http://bit.ly/kaggletrain', nrows=10)
X = df[cols]
y = df['Survived']

df_new = pd.read_csv('http://bit.ly/kaggletest', nrows=10)
X_new = df_new[cols]

ohe = OneHotEncoder()

ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']),
    remainder='passthrough')

logreg = LogisticRegression(solver='liblinear', random_state=1)

pipe = make_pipeline(ct, logreg)
pipe.fit(X, y)
pipe.predict(X_new)

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

# Part Four
Encoding test data

# References
We report here relevant references:
1. author1, article1, journal1, year1, url1
2. author2, article2, journal2, year2, url2